### ISSUE TITLE
Paths: macros aren't expanded properly in sub-packages

### ISSUE THREAD

**Issue by ermo** [serpent-os/moss-format#2]
Thank you to @livingsilver94 for the bug report.

Repro:

```yaml
packages :
    - "%(name)-staticlibs":
        summary: Static libraries
        description: Not really useful but for testing
        paths:
            - "%(libdir)/*.a"
```
